# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'ngaeli-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Fakte interesante',  url: 'fak'}
- {name: 'Meso', url: 'resources'}
- {name: 'Postime',       url: 'ss'}
- {name: 'Dokumente',      url: 'dok'}
- {name: 'Nga une',              url: 'ngaune'}
- {name: 'Kontakte',            url: 'kont'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/'}
- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://instagram.com'}
- {icon: 'envelope', link:   ''}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Te reja'
  previous_page: 'Me te vjetra'

sharing_button_prompt: 'mos hezito te shperndash kte faqe fantastike'

related_posts: 'te tjera...'

post_date_prefix: ''
